###############################################################################
# config.toml
#
# Hugo configuration file.
#
# See the following for documentation:
#   * https://gohugo.io/getting-started/configuration
###############################################################################

baseURL = "https://infrable.io"
languageCode = "en-us"
title = "Infrable"

theme = "infrable-io"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  under_construction = false

  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.home]
    show_contact_box = true
    show_contact_button = true
    show_services_button = true

  # The following can be used to display a different logo on mobile and desktop
  # devices.
  [params.logo]
    mobile = "images/logo/logo-mobile.png"
    mobile_height = "50px"
    desktop = "images/logo/logo-desktop.png"
    desktop_height = "50px"
    alt = "Infrable - Your Infrastructure As Code"

  [params.seo]
    meta_description = "Your Infrastructure As Code"
    meta_og_description = "Your Infrastructure As Code"
    meta_og_image = ""
    meta_og_site_name = "Infrable"
    meta_og_title = "Infrable - Your Infrastructure As Code"
    meta_twitter_creator = "@infrable_io"
    meta_twitter_description = "Your Infrastructure As Code"
    meta_twitter_image = ""
    meta_twitter_site = "@infrable_io"
    meta_twitter_title = "Infrable - Your Infrastructure As Code"

  [params.footer]
    copyright_text = "Infrable - Your Infrastructure As Code"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 2

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 3

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 4

  [[menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 5

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 6

  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
