###############################################################################
# config.toml
#
# Hugo configuration file.
#
# See the following for documentation:
#   * https://gohugo.io/getting-started/configuration
###############################################################################

baseURL = "https://infrable.io"
languageCode = "en-us"
title = "Infrable.io"

theme = "infrable-io"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true
    show_services_button = true

  [params.logo]
    mobile = "images/logo/logo-mobile.png"
    mobile_height = "36px"
    desktop = "images/logo/logo-desktop.svg"
    desktop_height = "36px"
    alt = "Infrable.io - Your Infrastructure As Code"

  [params.seo]
    meta_twitter_site = "@infrable_io"
    meta_twitter_creator = "@infrable_io"

  [params.team]
    summary_large_truncate = 120

  [params.footer]
    copyright_text = "Infrable.io - Your Infrastructure As Code"

[menu]
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3

  [[menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 4

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 5

  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
