###############################################################################
# theme.toml
#
# Hugo theme configuration file.
#
# See the following for an example:
#   * https://github.com/gohugoio/hugoThemes#themetoml
###############################################################################

name = 'infrable-io'
license = 'MIT'
licenselink = 'https://github.com/infrable-io/infrable-io/blob/master/LICENSE'
description = 'A Hugo theme for infrable.io'

homepage = 'https://github.com/infrable-io/infrable-io'
demosite = 'https://infrable.io'

[author]
  name = 'Infrable'
  homepage = 'https://infrable.io'
