###############################################################################
# theme.toml
#
# Hugo theme configuration file.
#
# See the following for an example:
#   * https://github.com/gohugoio/hugoThemes#themetoml
###############################################################################

name = "infrable-io"
license = "MIT"
licenselink = "https://github.com/infrable-io/infrable-io/blob/master/site/themes/infrable-io/LICENSE"
description = "A theme for Infrable.io"
homepage = "https://github.com/infrable-io/infrable-io/tree/master/site/themes/infrable-io"
demosite = "https://infrable.io"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Infrable.io"
  homepage = "https://infrable.io"
